### ISSUE TITLE
Update your links

### ISSUE THREAD

**Issue by alfawal** [Pyroseza/Pyroseza#1]
Hello,
This is your HR specialist from a Fortune 500 reviewing your profile, please fix your links on line 65 and 69.
https://github.com/Pyroseza/Pyroseza/blob/e389efa29094b31aae073586e026f211c23552fc/README.md?plain=1#L65-L69

Just kidding, I don't like to play ranked :D

**Comment by Pyroseza** [comment]
Thanks for spotting that!
